version: 2
jobs:
  env:
    # Ref.: https://circleci.com/docs/2.0/configuration-reference/#machine
    machine:
      image: "ubuntu-1604:201903-01"
    steps:
    - checkout
    - run:
        name: "Print environment variables"
        command: |
          env
          pwd
          find
workflows:
  version: 2
  all_workflow:
    jobs:
    - env
